
name: Main Jobs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: docker build . --file Dockerfile --tag flaskactions

      - name: IfMerged
        if: ${{ github.event.pull_request.merged }}
        run: echo "merged"
